cat > kubernetes/deployment.yaml << 'EOF'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-test-app
  labels:
    app: cicd-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-test-app
  template:
    metadata:
      labels:
        app: cicd-test-app
    spec:
      containers:
      - name: cicd-test-app
        image: your-docker-repo/cicd-test-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: ENVIRONMENT
          value: "kubernetes"
        - name: VERSION
          value: "1.0.0"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
EOF
